# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-27 00:42
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoxScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seconds_played', models.IntegerField()),
                ('field_goals', models.IntegerField()),
                ('field_goal_attempts', models.IntegerField()),
                ('three_point_field_goals', models.IntegerField()),
                ('three_point_field_goal_attempts', models.IntegerField()),
                ('free_throws', models.IntegerField()),
                ('free_throw_attempts', models.IntegerField()),
                ('offensive_rebounds', models.IntegerField()),
                ('defensive_rebounds', models.IntegerField()),
                ('total_rebounds', models.IntegerField()),
                ('assists', models.IntegerField()),
                ('steals', models.IntegerField()),
                ('blocks', models.IntegerField()),
                ('turnovers', models.IntegerField()),
                ('fouls_committed', models.IntegerField()),
                ('points', models.IntegerField()),
                ('draftkings_points', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='DraftkingsPlayerSalary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('abbreviation', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_year', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('abbreviation', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='team',
            unique_together=set([('name', 'abbreviation')]),
        ),
        migrations.AlterUniqueTogether(
            name='position',
            unique_together=set([('name', 'abbreviation')]),
        ),
        migrations.AddField(
            model_name='player',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Position'),
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Team'),
        ),
        migrations.AddField(
            model_name='game',
            name='away_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_team', to='data.Team'),
        ),
        migrations.AddField(
            model_name='game',
            name='home_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_team', to='data.Team'),
        ),
        migrations.AddField(
            model_name='game',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Season'),
        ),
        migrations.AddField(
            model_name='draftkingsplayersalary',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Game'),
        ),
        migrations.AddField(
            model_name='draftkingsplayersalary',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Player'),
        ),
        migrations.AddField(
            model_name='boxscore',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Game'),
        ),
        migrations.AddField(
            model_name='boxscore',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Player'),
        ),
        migrations.AlterUniqueTogether(
            name='player',
            unique_together=set([('first_name', 'last_name', 'team', 'position')]),
        ),
        migrations.AlterUniqueTogether(
            name='game',
            unique_together=set([('home_team', 'away_team', 'start_time')]),
        ),
        migrations.AlterUniqueTogether(
            name='draftkingsplayersalary',
            unique_together=set([('game', 'player', 'salary')]),
        ),
        migrations.AlterUniqueTogether(
            name='boxscore',
            unique_together=set([('player', 'game')]),
        ),
    ]
