# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-13 00:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('source_id', models.CharField(max_length=250, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='GamePlayerBoxScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
                ('explanation', models.CharField(default=None, max_length=250, null=True)),
                ('seconds_played', models.BigIntegerField(null=True)),
                ('field_goals_made', models.BigIntegerField(null=True)),
                ('field_goals_attempted', models.BigIntegerField(null=True)),
                ('three_point_field_goals_made', models.BigIntegerField(null=True)),
                ('three_point_field_goals_attempted', models.BigIntegerField(null=True)),
                ('free_throws_made', models.BigIntegerField(null=True)),
                ('free_throws_attempted', models.BigIntegerField(null=True)),
                ('offensive_rebounds', models.BigIntegerField(null=True)),
                ('defensive_rebounds', models.BigIntegerField(null=True)),
                ('assists', models.BigIntegerField(null=True)),
                ('steals', models.BigIntegerField(null=True)),
                ('blocks', models.BigIntegerField(null=True)),
                ('turnovers', models.BigIntegerField(null=True)),
                ('personal_fouls', models.BigIntegerField(null=True)),
                ('plus_minus', models.BigIntegerField(null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Game')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('source_id', models.CharField(max_length=250, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(unique=True)),
                ('end_time', models.DateTimeField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TeamPlayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Team')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='player',
            unique_together=set([('name', 'source_id')]),
        ),
        migrations.AddField(
            model_name='gameplayerboxscore',
            name='team_player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.TeamPlayer'),
        ),
        migrations.AddField(
            model_name='game',
            name='away_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_team', to='data.Team'),
        ),
        migrations.AddField(
            model_name='game',
            name='home_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_team', to='data.Team'),
        ),
        migrations.AddField(
            model_name='game',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Season'),
        ),
        migrations.AlterUniqueTogether(
            name='teamplayer',
            unique_together=set([('team', 'player')]),
        ),
        migrations.AlterUniqueTogether(
            name='gameplayerboxscore',
            unique_together=set([('game', 'team_player')]),
        ),
        migrations.AlterUniqueTogether(
            name='game',
            unique_together=set([('home_team', 'away_team', 'season', 'start_time')]),
        ),
    ]
