# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-30 00:32
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyFantasySportsSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerSalary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.FloatField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Player')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.DailyFantasySportsSite')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='draftkingsplayersalary',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='draftkingsplayersalary',
            name='game',
        ),
        migrations.RemoveField(
            model_name='draftkingsplayersalary',
            name='player',
        ),
        migrations.DeleteModel(
            name='DraftkingsPlayerSalary',
        ),
        migrations.AlterUniqueTogether(
            name='playersalary',
            unique_together=set([('site', 'game', 'player', 'salary')]),
        ),
    ]
