# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-12 03:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='jersey_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterUniqueTogether(
            name='player',
            unique_together=set([('name', 'position', 'team', 'season', 'jersey_number')]),
        ),
    ]
