# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-23 01:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20160923_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traditionalboxscore',
            name='assists',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='traditionalboxscore',
            name='blocks',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='traditionalboxscore',
            name='defensive_rebounds',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='traditionalboxscore',
            name='field_goal_attempts',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='traditionalboxscore',
            name='field_goals',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='traditionalboxscore',
            name='fouls_committed',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='traditionalboxscore',
            name='free_throw_attempts',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='traditionalboxscore',
            name='free_throws',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='traditionalboxscore',
            name='offensive_rebounds',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='traditionalboxscore',
            name='plus_minus',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='traditionalboxscore',
            name='seconds_played',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='traditionalboxscore',
            name='steals',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='traditionalboxscore',
            name='three_point_field_goal_attempts',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='traditionalboxscore',
            name='three_point_field_goals',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='traditionalboxscore',
            name='turnovers',
            field=models.IntegerField(null=True),
        ),
    ]
