# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-08 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20151230_0032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playersalary',
            name='salary',
            field=models.IntegerField(),
        ),
    ]
